### ISSUE TITLE
These shortcuts in picture only works within bracket.

### ISSUE THREAD

**Issue by kisnows** [joshnh/CSS-Snippets#7]
![test](https://cloud.githubusercontent.com/assets/9394000/5563623/a4abb354-8ebf-11e4-9892-1375731559d5.gif)

**Comment by joshnh** [comment]
@kisnows Would you mind writing out exactly what the issue is?

**Comment by kisnows** [comment]
@joshnh Embarrassed,my english is not well,i'll try to expess what the issue is:
Some snippets just work in bracket.If out of brackets, the `CSS-Snippets` doesn't work,just like the picture show.
For examle,if I input `hov` in bracket and enter `Tab`,it will show the correct representation：

	:hover,
	  :focus {
		
	  }
,but if  I input `hov` out of bracket, it just show `overflow: hidden;`.
Is i expess clear?

**Comment by joshnh** [comment]
Yeah, I understand. I'm not entirely sure what is happening. Hopefully when I get some time I can figure it out. Thanks.

**Comment by ashleyjenniker** [comment]
If you edit the hover snippet and change it to the below then it solves the above. Same thing can be done for the active snippet

`<snippet>
<content><![CDATA[$1:hover,
$1:focus $2]]></content>
	<tabTrigger>hov</tabTrigger>
    <description>CSS - :hover, :focus</description>
    <scope>source.css, source.less, source.scss, source.stylus</scope>
</snippet>`

**Comment by ashleyjenniker** [comment]
[https://github.com/skuroda/PackageResourceViewer](url)

**Comment by joshnh** [comment]
Thanks for letting me know, Ashley. I'll make that change now to both hover and active snippets.
