### ISSUE TITLE
Cross browser support

### ISSUE THREAD

**Issue by ashleyjenniker** [joshnh/CSS-Snippets#9]
Not all CSS has cross browser support. Haven't checked everything yet but I've only picked up the 'border-radius' as its the most common one I use.

**Comment by ashleyjenniker** [comment]
Solved the problem by editing the snippet

`
<snippet>
	<content><![CDATA[-webkit-border-radius: 1px;
   -moz-border-radius: 1px;
        border-radius: 1px;]]></content>
	<tabTrigger>bor</tabTrigger>
    <description>CSS - border-radius: ;</description>
    <scope>source.css, source.less, source.scss, source.stylus</scope>
</snippet>
`

**Comment by joshnh** [comment]
Thanks, Ashley. The moz prefix hasn't been required for a long time, so unless a visitor is using a very old browser, the current snippet should be perfectly fine.
